#!/bin/bash
# Script to handle locking the screen

xset +dpms dpms 5 5 5
playerctl -a pause
polychromatic-cli -o brightness -p 0
dunstctl set-paused true
#pactl set-sink-mute @DEFAULT_SINK@ true

IMAGE="$HOME/.config/autorandr/$(autorandr --current)/lock.png"
if ! [ -e $IMAGE ]; then
    IMAGE=$HOME/sync/wallpapers/desktop.png
fi
#i3lock -i $IMAGE -fen

# This is rather sad, but idrc
lock_command='betterlockscreen -l'
~/scripts/log.sh lock
time_locked=$(/usr/bin/time -f '%E' bash -c "$lock_command &> /dev/null" 2>&1)

xset dpms 0 0 0
dunstctl set-paused false

notify-send 'Time Locked:' "$time_locked" -r 1238129238 -u low
~/scripts/log.sh unlock

#pactl set-sink-mute @DEFAULT_SINK@ false # TODO: make this resume the previous state

polychromatic-cli -o brightness -p 100

xinput --list | grep "QDtech" > /dev/null && xinput --map-to-output "QDtech MPI7003" HDMI-A-0
