#!/bin/bash
# Script to handle locking the screen

xset +dpms dpms 5 5 5
playerctl pause
polychromatic-cli -o brightness -p 0

IMAGE="$HOME/.config/autorandr/$(autorandr --current)/lock.png"
if ! [ -e $IMAGE ]; then
    IMAGE=$HOME/sync/wallpapers/desktop.png
fi
i3lock -i $IMAGE -fen

xset dpms 0 0 0

polychromatic-cli -o brightness -p 100

xinput --list | grep "QDtech" > /dev/null && xinput --map-to-output "QDtech MPI7003" HDMI-A-0
