#!/bin/sh
# stolen and modified from https://github.com/jonhoo/configs/blob/master/bins/bin/adjust-brightness
#
# BIG NOTE:
# In order for this script to work, it must _either_ be run as root (i.e. with sudo or actually as root)
# OR the following command must be run to allow editing of the brightness from normal users:
#     # sudo chmod 0666 /sys/class/backlight/intel_backlight/brightness

shopt -s extglob

cur_brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

step=$(printf "%.0f" "$(echo "0.10 * $max_brightness" | bc -l)")

case "$1" in
	+)
		new_brightness="$(echo "$cur_brightness + $step" | bc -l)";
		;;
	-)
		new_brightness="$(echo "$cur_brightness - $step" | bc -l)";
		;;
	(+([0-9]))
        if (($1 > 100)); then
            echo "Percent must be within [0, 100]"
            exit 1
        fi
        new_brightness="$(printf "%.0f" "$(echo "$1 * $max_brightness / 100" | bc -l)")";
        ;;
    *)
		echo "Usage: $0 +|-|<percent>"
		exit 1
		;;
esac

min_brightness="$(printf "%.0f" "$(echo "0.10 * $max_brightness" | bc -l)")"
if ((new_brightness < $min_brightness)); then
    new_brightness=$min_brightness
fi

if ((new_brightness > max_brightness)); then
	new_brightness="$max_brightness"
fi

new_percent="$(printf "%.0f" "$(echo "$new_brightness * 100 / $max_brightness" | bc -l)")"

echo "$cur_brightness -> $new_brightness / $max_brightness"
echo "$new_brightness" | tee /sys/class/backlight/intel_backlight/brightness

notify-send "Brightness set to $new_percent%"  -r 1238129239 -u low -t 500
