#!/bin/sh

s=""

if [ $# -eq 0 ]; then 
    cur=$(xinput list-props 13 | grep 'Device Enabled' | awk '{ print $NF }')
    if [ $cur = "1" ]; then 
        s="0"
    else
        s="1"
    fi
elif [ $1 = "on" ]; then
    s="1"
elif [ $1 = "off" ]; then
    s="0"
else
    echo "Unknown arguments: $@" >&2
    exit 1
fi

xinput list |
    grep -i 'touchpad' |
    awk '{print $6}' |
    cut -d'=' -f2 |
    xargs -I'{}' xinput set-prop {} "Device Enabled" "$s"

if [ $s = "1" ]; then
    echo "Touchpad Enabled"
else
    echo "Touchpad Disabled"
fi
